const data = {
    Capital: null,
    CompanyDetail: null,
    Companyname: null,
    ESizeEx: null,
    ESizeTotal: null,
    EsizeLocal: null,
    ForecastAnnualRevenue: null,
    ForecastDomesticSCR: null,
    ForecastDomesticUSD: null,
    LiabilityCoverage: "",
    LoanYN: "",
    OperationType: "0",
    ProposedIndemnityCover: ".0000",
    Signature: "",
    SignedBy: "",
    SignedOn: "1900-01-01",
    TicketReference: null,
    TrainingProgramDetail: "",
    address1: null,
    address2: null,
    address_id: "0",
    caddress: null,
    city: null,
    companyemail:  null,
    companyfax:  null,
    companymobile: null,
    country_id: null,
    countryname: null,
    created_at: null,
    id: null,
    incorporationdate: null,
    isFSP: false,
    isICSP: false,
    isITSP: false,
    isdraft: null,
    ownerequityYN: null,
    process_id: "700",
    shareholderequityYN: null,
    state: null,
    webuser_id: null,
    webusertask_id: null,
    zip: null
};

export default data;